# Changes here will be overwritten by Copier
_commit: 9312d8b
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2022'
documentation: false
email: bluetooth@koston.org
full_name: J. Nick Koston
github_username: bluetooth-devices
initial_commit: true
open_source_license: MIT
package_name: mopeka_iot_ble
project_name: Mopeka IOT BLE
project_short_description: Mopeka IOT BLE Parser
project_slug: mopeka-iot-ble
run_poetry_install: true
setup_github: true
setup_pre_commit: true

